# Generated by Django 5.1 on 2025-12-09 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tienda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
