# Generated by Django 5.1 on 2025-12-09 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tienda', '0002_alter_libro_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='numero_pedido',
            field=models.CharField(editable=False, max_length=32, unique=True),
        ),
    ]
