# Generated by Django 5.1 on 2025-12-09 01:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tienda', '0003_alter_pedido_numero_pedido'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historialpedido',
            options={'ordering': ['-fecha_registro'], 'verbose_name': 'Historial de Pedido', 'verbose_name_plural': 'Historial de Pedidos'},
        ),
        migrations.RenameField(
            model_name='historialpedido',
            old_name='fecha',
            new_name='fecha_registro',
        ),
        migrations.AlterField(
            model_name='historialpedido',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historialpedido',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historial_usuario', to=settings.AUTH_USER_MODEL),
        ),
    ]
